### ISSUE TITLE
this is illegal in many US countries

### ISSUE THREAD

**Issue by shmuel-web** [TechForPalestine/boycott-israeli-tech-companies-dataset#10]
I hope you have a good lawyer :)
[https://en.wikipedia.org/wiki/Anti-BDS_laws](https://en.wikipedia.org/wiki/Anti-BDS_laws)

**Comment by hosamaly** [comment]
Indeed, it's probably safer to keep this repository (or at least a mirror of it) on GitLab. Whereas GitHub is an American company subject to US laws, GitLab is a Ukrainian company.

**Comment by pbiggar** [comment]
BDS laws don't work like that.
