### ISSUE TITLE
Please add Amazon (AWS)

### ISSUE THREAD

**Issue by frankiesimon** [TechForPalestine/boycott-israeli-tech-companies-dataset#16]
Amazon has a development center in Israel so I don't think any usage of AWS is legit if you want to boycott tech companies supporting Israel. Good luck :)

**Comment by sapsap18** [comment]
Its okay just use Azure as an alternative
oh wait... nevermind...

**Comment by liranelisha** [comment]
maybe GC? o no....

**Comment by pbiggar** [comment]
Troll afaict
