### ISSUE TITLE
Missing alternatives and sources

### ISSUE THREAD

**Issue by sapsap18** [TechForPalestine/boycott-israeli-tech-companies-dataset#22]
I've been wanting to replace my Mobileye device, to help #ceasefire and #freepalestine, but the list of alternatives seems to be empty. 

I also think that the following products/companies should be added for this list to have a better impact:

- The Iron Dome - would make bombing Israel a lot easier and safer (for the #freedom_fighters)
- ZayinBaayin - Israel's leading AR and VR device manufacturer 
- JachnoonCall - An Israeli telecommunication company 

Thanks in advance and keep up the good work!

**Comment by pbiggar** [comment]
Closing this for violating the community rule against advocating violence:

> The Iron Dome - would make bombing Israel a lot easier and safer (for the #freedom_fighters)
